config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :sessions,only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :pictures do
    resources :comments
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture
  validates :content, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length:{ maximum:100}
  validates :production_year, presence: true
  validates :running_time, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :content, presence: true, length:{in: 1..500}
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :comments,dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures
  mount_uploader :user_image, ImageUploader
  validates :name, presence: true, length:{ maximum: 30 }
  validates :email, presence: true, length:{ maximum: 200 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password_digest, presence: true, length:{ minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def authenticate_user
    if @current_user == nil
      flash[:notice] = t('notice.login_needed')
      redirect_to new_session_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_picture, only:[:create, :edit, :update]

  def create
    @picture = Picture.find(params[:picture_id])
    @comment = @picture.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { redirect_to picture_path(@picture), notice:"投稿できませんでした" }
      end
    end
  end

  def edit
    @comment = @picture.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
   @comment = @picture.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        flash.now[:notice] = 'コメントが編集されました'
        format.js { render :index }
      else
        flash.noq[:notice] = 'コメントの編集に失敗しました'
        format.js { render :edit_error }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end

  private

  def set_picture
    @picture = Picture.find(params[:picture_id])
  end

  def comment_params
    params.require(:comment).permit(:picture_id, :content)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_all_pictures, only:[:index, :create, :confirm]
  before_action :set_picture, only:[:show, :edit, :update, :destroy]
  def index
    @picture = current_user.pictures.new
  end

  def create
    @picture = current_user.pictures.new(picture_params)
    if params[:back]
      render :index
    else
      if @picture.save
        redirect_to pictures_path, notice:"新規投稿しました"
      else
        render :index
      end
    end
  end

  def show
    @comments = @picture.comments
    @comment = @picture.comments.build
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice:"投稿を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @picture.delete
    redirect_to pictures_path, notice:"投稿を削除しました"
  end

  def confirm
    @picture = current_user.pictures.new(picture_params)
    render :index if @picture.invalid?
  end

  private
  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end
  def set_all_pictures
    @pictures = Picture.all.order("created_at DESC")
  end
  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to pictures_path
    end
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id), notice:"ログインしました"
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    redirect_to new_session_path, notice:"ログアウトしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, notice:'アカウントを作成しました'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice:'プロフィールを編集しました'
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:user_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message(message,klass)
    content_tag(:div,class: "alert alert-#{klass}") do
      concat raw(message)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'edit'
      picture_path(@picture.id)
    else
      confirm_pictures_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_edit.html.erb
<!-- この記述がblogのshow画面に表示されるコメント入力欄になります -->
<%= form_with(model: [picture, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content , id:"comment_content_#{picture.id}" %>
    <%= form.label :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<!-- この記述がblogのshow画面に表示されるコメント入力欄になります -->
<%= form_with(model: [picture, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <div class="comment-content" id ="this_comment_<%= comment.id %>" ></div>
        <p><%= comment.content %></p>
        <p><%= link_to "コメント編集", edit_picture_comment_path(picture, comment ), remote: true %></p>
        <p><%= link_to "コメント削除", picture_comment_path(comment.picture_id, comment.id), method: :delete, remote: true, data:{ confirm: "本当に削除しますか？" }%></p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', picture: @picture, comment: @comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.picture.comments, picture: @comment.picture }) %>");
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>FaceClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  </head>

  <body>
    <header>
      <div class="header-menu">
      <% if logged_in? %>
        <%= link_to pictures_path ,{class:"home"} do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#2F72FF" class="menu-btn" viewBox="0 0 16 16">
            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
          </svg>
        <% end %>
        <span class="home-pop">トップページ</span>
        <%= link_to user_path(current_user.id) ,{class:"user-info"} do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#2F72FF" class="menu-btn" viewBox="0 0 16 16">
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
          </svg>
        <% end %>
        <span class="user-info-pop">ユーザー情報</span>
        <%= link_to session_path(current_user.id), {method: :delete, class:"logout-btn"} do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#2F72FF" class="menu-btn" viewBox="0 0 16 16">
            <path d="M1.5 15a.5.5 0 0 0 0 1h13a.5.5 0 0 0 0-1H13V2.5A1.5 1.5 0 0 0 11.5 1H11V.5a.5.5 0 0 0-.57-.495l-7 1A.5.5 0 0 0 3 1.5V15H1.5zM11 2h.5a.5.5 0 0 1 .5.5V15h-1V2zm-2.5 8c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z"/>
          </svg>
        <% end %>
        <span class="logout-btn-pop">ログアウト</span>
      <% else %>
        <%= link_to new_user_path, {class:"signup-btn"} do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#2F72FF" class="menu-btn" viewBox="0 0 16 16">
            <path d="M8 2a5.53 5.53 0 0 0-3.594 1.342c-.766.66-1.321 1.52-1.464 2.383C1.266 6.095 0 7.555 0 9.318 0 11.366 1.708 13 3.781 13h8.906C14.502 13 16 11.57 16 9.773c0-1.636-1.242-2.969-2.834-3.194C12.923 3.999 10.69 2 8 2zm2.354 4.854l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708.708z"/>
          </svg>
        <% end %>
        <span class="signup-btn-pop">サインアップ</span>
        <%= link_to new_session_path,{class:"login-btn"} do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#2F72FF" class="menu-btn" viewBox="0 0 16 16">
            <path d="M12 1a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2a1 1 0 0 1 1-1h8zm-2 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
          </svg>
        <% end %>
        <span class="login-btn-pop">ログイン</span>
      <% end %>
      </div>
    </header>
    <div class="main-content">
      <%= flash_message(flash[:success], :success) if flash[:success] %>
      <%= flash_message(flash[:danger], :danger) if flash[:danger] %>
      <%= flash_message(flash[:error], :worning) if flash[:error] %>
      <%= flash_message(flash[:notice], :info) if flash[:notice] %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<div class="content-card">
  <%= form_with(model: @picture, url: choose_new_or_edit ,local: true, class:"form-wrap") do |f| %>
   <% if @picture.errors.any? %>
  <div class="errors_explain alert alert-danger">
      <% @picture.errors.full_messages.each do |message| %>
      <p><%= message %></p>
      <% end %>
  </div>
  <% end %>
  <div class="content-card-top">
    <% if current_user.user_image.url == nil %>
    <img src="https://placehold.jp/50x50.png" class="avatar">
    <% else %>
    <%= image_tag current_user.user_image.url ,class:"avatar"%>
    <% end %>
    <span class="user-name"><%= current_user.name %></span>
  </div>
  <div>
    <%= f.text_area :content, placeholder:"#{current_user.name}さん、その気持ちをシェアしよう" ,class:"content-form",wrap:"soft" %>
  </div>
  <div  class="form-bottom">
    <label class="file-btn">
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#2F72FF" class="bi bi-card-image" viewBox="0 0 16 16">
      <path d="M6.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
      <path d="M1.5 2A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13zm13 1a.5.5 0 0 1 .5.5v6l-3.775-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062L1.002 12v.54A.505.505 0 0 1 1 12.5v-9a.5.5 0 0 1 .5-.5h13z"/>
      </svg>
      <%= f.file_field :image ,class:"choose-picture"%>
    </label>
    <span class="file-pop">画像を添付</span>
    <label class="submit-btn no-click">
      <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="#8baffc" class="bi bi-upload" viewBox="0 0 16 16">
      <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
      <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z"/>
    </svg>
      <%= f.submit %>
    </label>
    <span class="submit-pop">送信する</span>
  </div>
  <% end %>
</div>

app/views/pictures/confirm.html.erb
<h2>こちらで投稿しますか？</h2>
<div  class="content-card">
  <%= form_with(model: @picture ,local: true) do |f| %>
  <%= f.hidden_field :content %>
  <%= f.hidden_field :image_cache %>
  <div class="card-content">
    <%= @picture.content %>
  </div>
  <% unless @picture.image.url == nil %>
  <div class="picture-space">
    <%= image_tag @picture.image.url %>
  </div>
  <% end %>
  <div class="card-bottom">
    <%= f.submit "投稿する", class:'btn btn-primary btn-sm' %>
    <%= f.submit "戻る", name:'back', class:'btn btn-secondary btn-sm' %>
  </div>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<div class="">
  <%= render 'form' %>
  <!-- <%= form_with(model: @picture, local: true) do |f| %>
  <%= f.text_field :content, placeholder:"その気持ちをシェアしよう"%>
  <%= f.file_field :image %>
  <%= f.submit %>
  <% end %> -->
</div>

app/views/pictures/index.html.erb
<div>
  <% if @picture.errors.any?  %>
  <ul>
    <% @picture.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
</div>
  <%= render 'form' %>
<div>
  <% @pictures.each do |picture| %>
    <div  class="content-card">
      <div class="card-top">
      <% if picture.user.user_image.url == nil %>
      <image src="https://placehold.jp/50x50.png" class="avatar">
      <% else %>
        <%= link_to user_path(picture.user.id) do %>
          <%= image_tag picture.user.user_image.url ,class:"avatar"%>
        <% end %>
      <% end %>
      <span class="user-name"><%= picture.user.name %></span>
      </div>
      <div class="card-content">
      <%= picture.content %>
      </div>
      <div class="picture-space">
      <% unless picture.image.url == nil %>
        <%= image_tag picture.image.url %>
      <% end %>
      </div>
      <div class="card-bottom">
        <span>
        <%= picture.created_at.strftime('%Y/%m/%d %H:%M')  %>
        </span>
        <span>
        <%= link_to "詳細", picture_path(picture.id) %>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/pictures/show.html.erb
<div  class="content-card">
  <div class="card-top">
    <% if @picture.user.user_image.url == nil %>
    <image src="https://placehold.jp/50x50.png" class="avatar">
    <% else %>
    <%= image_tag @picture.user.user_image.url ,class:"avatar"%>
    <% end %>
    <span class="user-name"><%= @picture.user.name %></span>
  </div>
  <div class="card-content">
    <%= @picture.content %>
  </div>
  <div class="picture-space">
    <% unless @picture.image.url == nil %>
      <%= image_tag @picture.image.url %>
    <% end %>
  </div>
  <div class="card-bottom">
    <% if @picture.user_id == current_user.id %>
    <%= link_to '編集', edit_picture_path(@picture.id), class:"btn btn-primary btn-sm" %>
    <%= link_to '削除', picture_path(@picture.id), {class:"btn btn-danger btn-sm", method: :delete} %>
  </div>
<% end %>
</div>
<!-- コメント一覧 -->

<div id="comments_area">
  <!-- 投稿されたコメント一覧をブログ詳細ページに表示するためのrender -->
  <%= render partial: 'comments/index', locals: { comments: @comments, picture: @picture } %>
</div>
<div>
  <!-- コメント入力欄をブログの詳細ページに表示するためのrender -->
  <%= render partial: 'comments/form', locals: { comment: @comment, picture: @picture } %>
  <%= link_to '編集', edit_picture_path(@picture) %> |
  <%= link_to '戻る', pictures_path %>
</div>

app/views/users/edit.html.erb
<h1>ユーザー情報の編集</h1>
<% if @user.errors.any? %>
<div id="errors_explanation">
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
<div class="user-edit-wrap">
  <table>
    <tr>
      <td><%= f.label :name, '名前' %></td>
    </tr>
    <tr>
      <td><%= f.text_field :name, placeholder:"name", class:"form-name" %></td>
    </tr>
    <tr>
      <td><%= f.label :email,'メールアドレス' %></td>
    </tr>
    <tr>
      <td><%= f.text_field :email, placeholder:"e-mail", class:"form-email"  %></td>
    </tr>
    <tr>
      <td><%= f.label :password,'パスワードを変更' %></td>
    </tr>
    <tr>
      <td><%= f.text_field :password, placeholder:"password", type:"password", class:"form-password" %></td>
    </tr>
    <tr>
      <td><%= f.label :user_image, 'ユーザー画像を設定' %></td>
    </tr>
    <tr>
      <td><%= f.file_field :user_image , class:"form-user-image" %></td>
    </tr>
    <tr>
      <td class="user-edit-image">
        <% unless @user.user_image.url == nil %>
          <%= image_tag @user.user_image.url %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td class="user-edit-submit">
        <%= f.submit '登録情報を変更する',class:"btn btn-primary btn-sm" %>
      </td>
    </tr>
  </table>
</div>
<% end %>

app/views/users/new.html.erb
<div class="session-form-wrap">
  <div class="flex-table">
    <h2>アカウント登録</h2>
    <% if @user.errors.any? %>
      <div class="errors_explanation alert alert-danger">
          <% @user.errors.full_messages.each do |message| %>
          <p><%= message %></p>
          <% end %>
      </div>
    <% end %>
    <%= form_with(model: @user, local: true) do |f| %>
    <div class="input-group mb-3">
      <%= f.text_field :name, placeholder:"name" %>
    </div>
    <div class="input-group mb-3">
      <%= f.text_field :email, placeholder:"e-mail" %>
    </div>
    <div class="input-group mb-3">
      <%= f.text_field :password, placeholder:"password",type:"password" %>
    </div>
    <div>
      <%= f.submit 'アカウント登録' ,class:"btn btn-primary btn-sm" %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %>さんのページ</h1>
<div class="user-edit-wrap">
  <table class="">
    <tr>
      <td>Email: <%= @user.email  %></td>
    </tr>
    <tr>
      <td class="user-edit-image">
      <% unless @user.user_image.url == nil %>
        <%= image_tag @user.user_image.url %>
      <% end %>
      </td>
    </tr>
    <tr>
      <% if @user.id == current_user.id %>
      <td class="align-center">
        <%= link_to 'ユーザー情報を編集', edit_user_path(@user.id), class:'btn btn-primary btn-sm' %>
        <%= link_to '新しく投稿する',pictures_path, class:'btn btn-primary btn-sm' %>
      </td>
      <% end %>
    </tr>
  </table>
</div>
<div>
  <% @user.pictures.each do |picture| %>
    <div  class="content-card">
      <div class="card-top">
      <% if picture.user.user_image.url == nil %>
      <image src="https://placehold.jp/50x50.png" class="avatar">
      <% else %>
      <%= image_tag picture.user.user_image.url ,class:"avatar"%>
      <% end %>
      <span class="user-name"><%= picture.user.name %></span>
      </div>
      <div class="card-content">
      <%= picture.content %>
      </div>
      <div class="picture-space">
      <% unless picture.image.url == nil %>
        <%= image_tag picture.image.url %>
      <% end %>
      </div>
      <div class="card-bottom">
        <span>
        <%= picture.created_at.strftime('%Y/%m/%d %H:%M')  %>
        </span>
        <span>
        <%= link_to "詳細", picture_path(picture.id) %>
        </span>
      </div>
    </div>
  <% end %>
</div>